### ISSUE TITLE
wiki server docs, Standalone section snippet issue

### ISSUE THREAD

**Issue by ewerybody** [EmbarkStudios/skyhook#3]
Hello 👋! just a tiny one:
Here in the wiki: https://github.com/EmbarkStudios/skyhook/wiki/The-server#standalone

the snippet doesn't work. I guess it should look like:
```py
from skyhook.server import Server
from skyhook.constants import HostPrograms

skyhook_server = Server()
skyhook_server.start_listening()
```
OR 

```py
import skyhook.server as shs
from skyhook.constants import HostPrograms

skyhook_server = shs.Server()
skyhook_server.start_listening()
```

Could probably even go simpler without the `HostPrograms` or have an example of making use of it in this context.
Thanks 😃
ëRiC

**Comment by nielsvaes** [comment]
Yeah you're right. Going to have to do a larger pass over all the wiki pages because I haven't kept them up to date unfortunately. The issue you outlined is fixed now.
